version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cypress
    versions:
    - 7.0.0
    - 7.0.1
    - 7.1.0
